### PR TITLE
Update packages

### PR DESCRIPTION
**Pull request by joshg4096**
- Upgrade to Angular 11
- Update dependencies

### CODE REVIEW

**Comment by mbukosky** [comment]
I'll review and push to a temp instance for testing. Please give me a day or so.

**Comment by mbukosky** [comment]
@joshg4096 the review app looks good to me. https://spotifyuncha-angular-11-gghabk.herokuapp.com/

If you are happy with the changes, I can merge and deploy the code.

**Comment by joshg4096** [comment]
LGTM

**Comment by mbukosky** [comment]
All done, great work!

**Pull request merged**
